// portfolio overlay
$(document).ready(function(){
    $("#work1").mouseover(function(){
      $("#box1").show();
    }).mouseout(function(){
      $("#box1").hide();
    });
  });
  $(document).ready(function(){
    $("#work2").mouseover(function(){
      $("#box2").show();
    }).mouseout(function(){
      $("#box2").hide();
    });
  });
  $(document).ready(function(){
    $("#work3").mouseover(function(){
      $("#box3").show();
    }).mouseout(function(){
      $("#box3").hide();
    });
  });
  $(document).ready(function(){
    $("#work4").mouseover(function(){
      $("#box4").show();
    }).mouseout(function(){
      $("#box4").hide();
    });
  });
  
  $(document).ready(function(){
    $("#work5").mouseover(function(){
      $("#box5").show();
    }).mouseout(function(){
      $("#box5").hide();
    });
    $("#work6").mouseover(function(){
      $("#box6").show();
    }).mouseout(function(){
      $("#box6").hide();
    });
    $("#work7").mouseover(function(){
      $("#box7").show();
    }).mouseout(function(){
      $("#box7").hide();
    });
    $("#work8").mouseover(function(){
      $("#box8").show();
    }).mouseout(function(){
      $("#box8").hide();
    });
  });
  
